#!/usr/bin/env sh
#
# Copyright (C) 2019 Anton Filatov <ya-enot@mail.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
etherusInstallBootstrap() (
    export LOG_LEVEL
    cat /etc/centos-release | grep -Eq '^Cent[Oo][Ss]\(?:\s+|release|\w+\)*\(7\.\d+\)\(\.?\d+\)?.*?$' || {
        echo "Installation is not supported for $(cat /etc/system-release 2>/dev/null || lsb_release -d 2>/dev/null || printf 'your system')" >&2
        exit -1
    }
    [ "$MODE" == "remote" ] || {
        echo "Please use online installation at https://validators.etherus.org" >&2
        exit -2
    }
    TMPFILE="$(mktemp /tmp/etherus-install.XXXXXX)" || {
        echo "Failed to create script temp file" >&2
        exit 1
    }
    trap "rm -f $TMPFILE" EXIT
    chmod 755 "$TMPFILE" || {
        echo "Failed to change temp script file permissions: $TMPFILE" >&2
        exit 2
    }
    curl -sL "https://raw.githubusercontent.com/ya-enot/etherctl/master/centos_7_install?$(date '+%Y-%m-%dT%H%M%S%z')" > "$TMPFILE" || {
        echo "Failed to download install script" >&2
        exit 3
    }
    command -v sudo &>/dev/null && {
        sudo -E "$TMPFILE" "${COMMAND:-install}" "$@" || {
            echo "Failed to run Etherus install script: $TMPFILE" >&2
            exit 4
        }
    } || {
        [ "$(id -u)" != "0" ] && {
            echo "You should act as superuser to install Etherus" >&2
            exit 5
        } || {
            "$TMPFILE" "${COMMAND:-install}" "$@" || {
                echo "Failed to run Etherus install script: $TMPFILE" >&2
                exit 4
            }
        }
    }
)
etherusInstallBootstrap
